service: kafka-connect

provider:
  name: kubeless
  runtime: python2.7

plugins:
  - serverless-kubeless

functions:
  kafka-connect:
    handler: kafka-connect.handler
    events:
      - trigger: 'dbserver1.inventory.customers'