apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: hello-yaml
spec:
  checksum: sha256:d251999dcbfdeccec385606fd0aec385b214cfc74ede8b6c9e47af71728f6e9a
  deps:
  function: |
    def foo(event, context):
        return "hello world"
  function-content-type: text
  handler: helloget.foo
  runtime: python2.7
  timeout: "180"
