# Default values for debezium mysql example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: debezium/example-mysql
  tag: 0.5
  pullPolicy: IfNotPresent
service:
  name: mysql
  type: ClusterIP
  externalPort: 3306
  internalPort: 3306

config:
  mysqlRootPassword: debezium
  mysqlUser: mysqluser
  mysqlPassword: mysqlpw
#resources:
#  limits:
#    cpu: 100m
#    memory: 512Mi
#  requests:
#    cpu: 100m
#    memory: 512Mi
